/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspv;

import java.io.File;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class aplikasi extends javax.swing.JFrame {
    int x=0;
    /**
     * Creates new form aplikasi
     */
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    protected void aktif(){
        tjumlahpaket.setEnabled(true);
        tjumlahpaket.requestFocus();
    }    
     
    protected void kosong(){
        cbpaket.setSelectedIndex(0);
        tjumlahpaket.setText("");
        cbbebekgoreng.setSelected(false);
        cbayamgoreng.setSelected(false);
        cbikannila.setSelected(false);
        cbkentanggoreng.setSelected(false);
        cbrotibakar.setSelected(false);
        cbspageti.setSelected(false);
        
        cbteh.setSelected(false);
        cbcappuchino.setSelected(false);
        cbjusmangga.setSelected(false);
        cbjusalpukat.setSelected(false);
        cbairmineral.setSelected(false);
        
        tnama.setText("");
        tnotlp.setText("");
    }
    
    protected void datatable1(){
    Object [] Baris = {"NOMOR MEJA","PILIHAN PAKET","JUMLAH PAKET","MAKANAN","MINUMAN","TOTAL HARGA","BAYAR","KEMBALIAN"};
    tabmode = new DefaultTableModel(null, Baris);
    tabelpembayaran.setModel(tabmode);
    try {
    String sql = "Select * from pembayaran";
    java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
            String a = hasil.getString("nomormeja");
            String b = hasil.getString("pilihanpaket");
            String c = hasil.getString("jumlahpaket");
            String d = hasil.getString("makanan");
            String e = hasil.getString("minuman");
            String f = hasil.getString("totalharga");
            String g = hasil.getString("bayar");
            String h = hasil.getString("kembalian");
            String[] data={a,b,c,d,e,f,g,h};
            tabmode.addRow(data);
            }
        }catch (Exception e){
            }
    }
    
    protected void datatable2(){
    Object [] Baris = {"NAMA","NOMOR TELEPON"};
    tabmode = new DefaultTableModel(null, Baris);
    tabelpelanggan.setModel(tabmode);
    try {
    String sql = "Select * from pelanggan";
    java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
            String a = hasil.getString("nama");
            String b = hasil.getString("notlp");
            String[] data={a,b};
            tabmode.addRow(data);
            }
        }catch (Exception e){
            }
    }
    
    public aplikasi() {
        initComponents();
        aktif();
        datatable1();
        datatable2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pemesanan = new javax.swing.JButton();
        pembayaran = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mp = new javax.swing.JPanel();
        mplaporan = new javax.swing.JPanel();
        penjualan = new javax.swing.JButton();
        struktransaksi = new javax.swing.JButton();
        mppemesanan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tnotlp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbpaket = new javax.swing.JComboBox<>();
        tjumlahpaket = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cbbebekgoreng = new javax.swing.JCheckBox();
        cbayamgoreng = new javax.swing.JCheckBox();
        cbikannila = new javax.swing.JCheckBox();
        cbspageti = new javax.swing.JCheckBox();
        cbrotibakar = new javax.swing.JCheckBox();
        cbkentanggoreng = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbteh = new javax.swing.JCheckBox();
        cbcappuchino = new javax.swing.JCheckBox();
        cbjusmangga = new javax.swing.JCheckBox();
        cbjusalpukat = new javax.swing.JCheckBox();
        cbairmineral = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpesanan = new javax.swing.JTable();
        breset = new javax.swing.JButton();
        btambah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bsimpandatapelanggan = new javax.swing.JButton();
        mppembayaran = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tnomormeja = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpembayaran = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ttotalharga = new javax.swing.JTextField();
        tbayar = new javax.swing.JTextField();
        tkembalian = new javax.swing.JTextField();
        bbersihkan = new javax.swing.JButton();
        bhitung = new javax.swing.JButton();
        bbayar = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bhitung2 = new javax.swing.JButton();
        bhapusdata = new javax.swing.JButton();
        mpdatapelanggan = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelpelanggan = new javax.swing.JTable();
        bubahdatapelanggan = new javax.swing.JButton();
        bhapusdatapelanggan = new javax.swing.JButton();
        bcetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BG.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Batang", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAYANI SEPENUH HATI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Batang", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("PILIH TRANSAKSI");

        pemesanan.setBackground(new java.awt.Color(255, 255, 0));
        pemesanan.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        pemesanan.setForeground(new java.awt.Color(204, 0, 0));
        pemesanan.setText("PEMESANAN");
        pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemesananActionPerformed(evt);
            }
        });

        pembayaran.setBackground(new java.awt.Color(255, 255, 0));
        pembayaran.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        pembayaran.setForeground(new java.awt.Color(204, 0, 0));
        pembayaran.setText("PEMBAYARAN");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        laporan.setBackground(new java.awt.Color(255, 255, 0));
        laporan.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        laporan.setForeground(new java.awt.Color(204, 0, 0));
        laporan.setText("LAPORAN");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Batang", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("SELAMAT DATANG MANAGER");

        jLabel4.setFont(new java.awt.Font("Batang", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FARHAN HAKIM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        mp.setBackground(new java.awt.Color(255, 255, 0));
        mp.setLayout(new java.awt.CardLayout());

        mplaporan.setBackground(new java.awt.Color(0, 0, 0));

        penjualan.setText("PENJUALAN");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });

        struktransaksi.setText("LAPORAN PELANGGAN");
        struktransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                struktransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mplaporanLayout = new javax.swing.GroupLayout(mplaporan);
        mplaporan.setLayout(mplaporanLayout);
        mplaporanLayout.setHorizontalGroup(
            mplaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mplaporanLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(struktransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
        mplaporanLayout.setVerticalGroup(
            mplaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mplaporanLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(mplaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(struktransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(528, Short.MAX_VALUE))
        );

        mp.add(mplaporan, "card4");

        mppemesanan.setBackground(new java.awt.Color(204, 0, 0));

        jLabel6.setFont(new java.awt.Font("Batang", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("NAMA    :");

        jLabel7.setFont(new java.awt.Font("Batang", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("NO TELPON   :");

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PILIH PAKET");

        cbpaket.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbpaket.setForeground(new java.awt.Color(204, 0, 0));
        cbpaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAKET A", "PAKET B", "PAKET C", "PAKET D", "PAKET E", "PAKET F" }));
        cbpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpaketActionPerformed(evt);
            }
        });

        tjumlahpaket.setFont(new java.awt.Font("Batang", 1, 12)); // NOI18N
        tjumlahpaket.setForeground(new java.awt.Color(204, 0, 0));
        tjumlahpaket.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel32.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("JUMLAH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(cbpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tjumlahpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tjumlahpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        jLabel15.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MENU MAKANAN");

        cbbebekgoreng.setBackground(new java.awt.Color(255, 255, 255));
        cbbebekgoreng.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbbebekgoreng.setForeground(new java.awt.Color(204, 0, 0));
        cbbebekgoreng.setText("BEBEK GORENG");
        cbbebekgoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbebekgorengActionPerformed(evt);
            }
        });

        cbayamgoreng.setBackground(new java.awt.Color(255, 255, 255));
        cbayamgoreng.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbayamgoreng.setForeground(new java.awt.Color(204, 0, 0));
        cbayamgoreng.setText("AYAM GORENG");

        cbikannila.setBackground(new java.awt.Color(255, 255, 255));
        cbikannila.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbikannila.setForeground(new java.awt.Color(204, 0, 0));
        cbikannila.setText("IKAN NILA");

        cbspageti.setBackground(new java.awt.Color(255, 255, 255));
        cbspageti.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbspageti.setForeground(new java.awt.Color(204, 0, 0));
        cbspageti.setText("SPAGETI");

        cbrotibakar.setBackground(new java.awt.Color(255, 255, 255));
        cbrotibakar.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbrotibakar.setForeground(new java.awt.Color(204, 0, 0));
        cbrotibakar.setText("ROTI BAKAR");

        cbkentanggoreng.setBackground(new java.awt.Color(255, 255, 255));
        cbkentanggoreng.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbkentanggoreng.setForeground(new java.awt.Color(204, 0, 0));
        cbkentanggoreng.setText("KENTANG GORENG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbspageti)
                    .addComponent(cbbebekgoreng)
                    .addComponent(cbayamgoreng)
                    .addComponent(cbikannila)
                    .addComponent(cbkentanggoreng)
                    .addComponent(cbrotibakar))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbebekgoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbayamgoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbikannila, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbkentanggoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbrotibakar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbspageti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbbebekgoreng.getAccessibleContext().setAccessibleName("");
        cbayamgoreng.getAccessibleContext().setAccessibleName("");
        cbikannila.getAccessibleContext().setAccessibleName("");
        cbspageti.getAccessibleContext().setAccessibleName("");
        cbrotibakar.getAccessibleContext().setAccessibleName("");
        cbkentanggoreng.getAccessibleContext().setAccessibleName("");

        jPanel6.setBackground(new java.awt.Color(255, 255, 0));

        jLabel23.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("MENU MINUMAN");

        cbteh.setBackground(new java.awt.Color(255, 255, 255));
        cbteh.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbteh.setForeground(new java.awt.Color(204, 0, 0));
        cbteh.setText("TEH");

        cbcappuchino.setBackground(new java.awt.Color(255, 255, 255));
        cbcappuchino.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbcappuchino.setForeground(new java.awt.Color(204, 0, 0));
        cbcappuchino.setText("CAPPUCHINO");

        cbjusmangga.setBackground(new java.awt.Color(255, 255, 255));
        cbjusmangga.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbjusmangga.setForeground(new java.awt.Color(204, 0, 0));
        cbjusmangga.setText("JUS MANGGA");

        cbjusalpukat.setBackground(new java.awt.Color(255, 255, 255));
        cbjusalpukat.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbjusalpukat.setForeground(new java.awt.Color(204, 0, 0));
        cbjusalpukat.setText("JUS ALPUKAT");

        cbairmineral.setBackground(new java.awt.Color(255, 255, 255));
        cbairmineral.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        cbairmineral.setForeground(new java.awt.Color(204, 0, 0));
        cbairmineral.setText("AIR MINERAL");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbteh)
                    .addComponent(cbcappuchino)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbairmineral)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbjusmangga)
                            .addComponent(cbjusalpukat))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(cbteh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbcappuchino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbjusmangga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbjusalpukat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbairmineral, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelpesanan.setBackground(new java.awt.Color(255, 255, 0));
        tabelpesanan.setFont(new java.awt.Font("Bodoni MT Black", 1, 11)); // NOI18N
        tabelpesanan.setForeground(new java.awt.Color(204, 0, 0));
        tabelpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PILIHAN PAKET", "JUMLAH PAKET", "MAKANAN", "MINUMAN"
            }
        ));
        tabelpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpesanan);

        breset.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        breset.setForeground(new java.awt.Color(204, 0, 0));
        breset.setText("RESET");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        btambah.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        btambah.setForeground(new java.awt.Color(204, 0, 0));
        btambah.setText("TAMBAH");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        bhapus.setForeground(new java.awt.Color(204, 0, 0));
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bsimpandatapelanggan.setText("SIMPAN DATA PELANGGAN");
        bsimpandatapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpandatapelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mppemesananLayout = new javax.swing.GroupLayout(mppemesanan);
        mppemesanan.setLayout(mppemesananLayout);
        mppemesananLayout.setHorizontalGroup(
            mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mppemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mppemesananLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mppemesananLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mppemesananLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tnotlp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bsimpandatapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mppemesananLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mppemesananLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        mppemesananLayout.setVerticalGroup(
            mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mppemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mppemesananLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mppemesananLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mppemesananLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mppemesananLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(mppemesananLayout.createSequentialGroup()
                        .addGroup(mppemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tnotlp)
                            .addComponent(tnama)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bsimpandatapelanggan))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))))
        );

        mp.add(mppemesanan, "card2");

        mppembayaran.setBackground(new java.awt.Color(0, 204, 0));

        jLabel21.setText("NO MEJA            :");

        tabelpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpembayaranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelpembayaran);

        jLabel29.setText("TOTAL HARGA    :");

        jLabel30.setText("BAYAR");

        jLabel31.setText("KEMBALIAN        :");

        bbersihkan.setText("BERSIHKAN");
        bbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihkanActionPerformed(evt);
            }
        });

        bhitung.setText("HITUNG");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });

        bbayar.setText("BAYAR");
        bbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbayarActionPerformed(evt);
            }
        });

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bhitung2.setText("HITUNG");
        bhitung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitung2ActionPerformed(evt);
            }
        });

        bhapusdata.setText("HAPUS");
        bhapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mppembayaranLayout = new javax.swing.GroupLayout(mppembayaran);
        mppembayaran.setLayout(mppembayaranLayout);
        mppembayaranLayout.setHorizontalGroup(
            mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mppembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mppembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tnomormeja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mppembayaranLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mppembayaranLayout.createSequentialGroup()
                                .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(mppembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bhitung2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bhapusdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bbersihkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bbayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(486, Short.MAX_VALUE))
        );
        mppembayaranLayout.setVerticalGroup(
            mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mppembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnomormeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbersihkan)
                    .addComponent(bhitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbayar)
                    .addComponent(bhitung2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bhapusdata)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        mp.add(mppembayaran, "card3");

        mpdatapelanggan.setBackground(new java.awt.Color(204, 0, 0));

        tabelpelanggan.setBackground(new java.awt.Color(255, 255, 0));
        tabelpelanggan.setFont(new java.awt.Font("Bodoni MT", 1, 11)); // NOI18N
        tabelpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelpelanggan);

        bubahdatapelanggan.setBackground(new java.awt.Color(255, 255, 0));
        bubahdatapelanggan.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        bubahdatapelanggan.setForeground(new java.awt.Color(204, 0, 0));
        bubahdatapelanggan.setText("UBAH");
        bubahdatapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahdatapelangganActionPerformed(evt);
            }
        });

        bhapusdatapelanggan.setBackground(new java.awt.Color(255, 255, 0));
        bhapusdatapelanggan.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        bhapusdatapelanggan.setForeground(new java.awt.Color(204, 0, 0));
        bhapusdatapelanggan.setText("HAPUS");
        bhapusdatapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusdatapelangganActionPerformed(evt);
            }
        });

        bcetak.setBackground(new java.awt.Color(255, 255, 0));
        bcetak.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        bcetak.setForeground(new java.awt.Color(204, 0, 0));
        bcetak.setText("CETAK");
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mpdatapelangganLayout = new javax.swing.GroupLayout(mpdatapelanggan);
        mpdatapelanggan.setLayout(mpdatapelangganLayout);
        mpdatapelangganLayout.setHorizontalGroup(
            mpdatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpdatapelangganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(mpdatapelangganLayout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(bubahdatapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(bhapusdatapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addGroup(mpdatapelangganLayout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mpdatapelangganLayout.setVerticalGroup(
            mpdatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpdatapelangganLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(mpdatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bubahdatapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhapusdatapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        mp.add(mpdatapelanggan, "card5");

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BGLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        String jenispaket;
        double hargapaket;
        jenispaket = String.valueOf(cbpaket.getSelectedItem());
        
        if (jenispaket.equals ("PAKET A")) {
            hargapaket = 30000;
        }else if (jenispaket.equals ("PAKET B")){
            hargapaket = 25000;
        }else if (jenispaket.equals ("PAKET C")){
            hargapaket = 25000;
        }else if (jenispaket.equals ("PAKET D")){
            hargapaket = 55000;
        }else if (jenispaket.equals ("PAKET E")){
            hargapaket = 45000;
        }else if (jenispaket.equals ("PAKET F")){
            hargapaket = 40000;
        }else {
            hargapaket = 0;
        }
        
        double jumlahpaket;
        jumlahpaket = Double.parseDouble(this.tjumlahpaket.getText());
        
        double hargamakanan = 0;
        if(cbbebekgoreng.isSelected()) {
            hargamakanan = 35000;
        }
        if(cbayamgoreng.isSelected()) {
            hargamakanan = 25000;
        }
        if(cbikannila.isSelected()) {
            hargamakanan = 25000;
        }
        if(cbkentanggoreng.isSelected()) {
            hargamakanan = 10000;
        }
        if(cbrotibakar.isSelected()) {
            hargamakanan = 15000;
        }
        if(cbspageti.isSelected()) {
            hargamakanan = 25000;
        }
        
        double hargaminuman = 0;
        if(cbteh.isSelected()) {
            hargaminuman = 5000;
        }
        if(cbcappuchino.isSelected()) {
            hargaminuman = 10000;
        }
        if(cbjusmangga.isSelected()) {
            hargaminuman = 15000;
        }
        if(cbjusalpukat.isSelected()) {
            hargaminuman = 15000;
        }
        if(cbairmineral.isSelected()) {
            hargaminuman = 5000;
        }
        
        double totalharga = ((hargapaket * jumlahpaket) + hargamakanan + hargaminuman);
        ttotalharga.setText(""+totalharga);
    }//GEN-LAST:event_bhitungActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        tabelpesanan.setValueAt(cbpaket.getSelectedItem(),x,0);
        tabelpesanan.setValueAt(tjumlahpaket.getText(),x,1);
        
        String makanan = "";
            if(cbbebekgoreng.isSelected())
                makanan="BEBEK GORENG";
            if(cbayamgoreng.isSelected())
                makanan="AYAM GORENG";
            if(cbikannila.isSelected())
                makanan="IKAN NILA";
            if(cbkentanggoreng.isSelected())
                makanan="KENTANG GORENG";
            if(cbrotibakar.isSelected())
                makanan="ROTI BAKAR";
            if(cbspageti.isSelected())
                makanan="SPAGETI";
        tabelpesanan.setValueAt(makanan,x,2);
        
        String minuman = "";
            if(cbteh.isSelected())
                minuman="TEH";
            if(cbcappuchino.isSelected())
                minuman="CAPPUCHINO";
            if(cbjusmangga.isSelected())
                minuman="JUS MANGGA";
            if(cbjusalpukat.isSelected())
                minuman="JUS ALPUKAT";
            if(cbairmineral.isSelected())
                minuman="AIR MINERAL";
        tabelpesanan.setValueAt(minuman,x,3);
        
        x=x+1;
    }//GEN-LAST:event_btambahActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        //remove panel
        mp.removeAll();
        mp.repaint();
        mp.revalidate();
        
        //add panel
        mp.add(mplaporan);
        mp.repaint();
        mp.revalidate();
    }//GEN-LAST:event_laporanActionPerformed

    private void pemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemesananActionPerformed
        mp.removeAll();
        mp.repaint();
        mp.revalidate();
        
        //add panel
        mp.add(mppemesanan);
        mp.repaint();
        mp.revalidate();
    }//GEN-LAST:event_pemesananActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        mp.removeAll();
        mp.repaint();
        mp.revalidate();
        
        //add panel
        mp.add(mppembayaran);
        mp.repaint();
        mp.revalidate();
    }//GEN-LAST:event_pembayaranActionPerformed

    private void tabelpesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpesananMouseClicked
        int bar = tabelpesanan.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        
        cbpaket.setSelectedItem(a);
        tjumlahpaket.setText(b);
        if(c.equals("BEBEK GORENG")) {cbbebekgoreng.setSelected(true);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
        
        if(c.equals("AYAM GORENG")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(true);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
        
        if(c.equals("IKAN NILA")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(true);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
        
       if(c.equals("KENTANG GORENG")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(true);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
       
       if(c.equals("ROTI BAKAR")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(true);
                                      cbspageti.setSelected(false);}
       
       if(c.equals("SPAGETI")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(true);}
       
       if(d.equals("TEH"))            {cbteh.setSelected(true);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(false);}
       
       if(d.equals("CAPPUCHINO"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(true);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(false);}
       
       if(d.equals("JUS MANGGA"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(true);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(false);}
       
       if(d.equals("JUS ALPUKAT"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(true);
                                      cbairmineral.setSelected(false);}
       
       if(d.equals("AIR MINERAL"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(true);}
    }//GEN-LAST:event_tabelpesananMouseClicked

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed

        kosong();
        
    }//GEN-LAST:event_bresetActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
       
        tabelpesanan.setValueAt("",tabelpesanan.getSelectedRow(),0);
        tabelpesanan.setValueAt("",tabelpesanan.getSelectedRow(),1);
        tabelpesanan.setValueAt("",tabelpesanan.getSelectedRow(),2);
        tabelpesanan.setValueAt("",tabelpesanan.getSelectedRow(),3);
    }//GEN-LAST:event_bhapusActionPerformed

    private void cbbebekgorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbebekgorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbebekgorengActionPerformed

    private void cbpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpaketActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String sql = "insert into pembayaran values (?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tnomormeja.getText());
            stat.setString(2, cbpaket.getSelectedItem().toString());
            stat.setString(3, tjumlahpaket.getText());
            
            String makanan="";
            if(cbbebekgoreng.isSelected())
                makanan="BEBEK GORENG";
            if(cbayamgoreng.isSelected())
                makanan="AYAM GORENG";
            if(cbikannila.isSelected())
                makanan="IKAN NILA";
            if(cbkentanggoreng.isSelected())
                makanan="KENTANG GORENG";
            if(cbrotibakar.isSelected())
                makanan="ROTI BAKAR";
            if(cbspageti.isSelected())
                makanan="SPAGETI";
            stat.setString(4, makanan);
            
            String minuman="";
            if(cbteh.isSelected())
                minuman="TEH";
            if(cbcappuchino.isSelected())
                minuman="CAPPUCHINO";
            if(cbjusmangga.isSelected())
                minuman="JUS MANGGA";
            if(cbjusalpukat.isSelected())
                minuman="JUS ALPUKAT";
            if(cbairmineral.isSelected())
                minuman="AIR MINERAL";
            stat.setString(5, minuman);
            
            stat.setString(6, ttotalharga.getText());
            stat.setString(7, tbayar.getText());
            stat.setString(8, tkembalian.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tnomormeja.requestFocus();
            datatable1();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bhitung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitung2ActionPerformed
        // TODO add your handling code here:
        double totalharga, totalbayar, totalkembalian;
        
        totalharga = Double.parseDouble(this.ttotalharga.getText());
        totalbayar = Double.parseDouble(this.tbayar.getText());
        
        totalkembalian = (totalbayar - totalharga);
        tkembalian.setText(""+totalkembalian);
    }//GEN-LAST:event_bhitung2ActionPerformed

    private void bhapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusdataActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok==0){
                String sql="delete from pembayaran where nomormeja='"+tnomormeja.getText()+"'";
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosong();
                    tnomormeja.requestFocus();
                    datatable1();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
            }
    }//GEN-LAST:event_bhapusdataActionPerformed

    private void tabelpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpembayaranMouseClicked
        // TODO add your handling code here:
        int bar = tabelpembayaran.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        String e = tabmode.getValueAt (bar, 4).toString();
        String f = tabmode.getValueAt (bar, 5).toString();
        String g = tabmode.getValueAt (bar, 6).toString();
        String h = tabmode.getValueAt (bar, 7).toString();
        
        tnomormeja.setText(a);
        cbpaket.setSelectedItem(b);
        tjumlahpaket.setText(c);
        if(d.equals("BEBEK GORENG")) {cbbebekgoreng.setSelected(true);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
        
        if(d.equals("AYAM GORENG")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(true);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
        
        if(d.equals("IKAN NILA")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(true);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
        
       if(d.equals("KENTANG GORENG")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(true);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(false);}
       
       if(d.equals("ROTI BAKAR")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(true);
                                      cbspageti.setSelected(false);}
       
       if(d.equals("SPAGETI")) {cbbebekgoreng.setSelected(false);
                                      cbayamgoreng.setSelected(false);
                                      cbikannila.setSelected(false);
                                      cbkentanggoreng.setSelected(false);
                                      cbrotibakar.setSelected(false);
                                      cbspageti.setSelected(true);}
       
       if(e.equals("TEH"))            {cbteh.setSelected(true);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(false);}
       
       if(e.equals("CAPPUCHINO"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(true);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(false);}
       
       if(e.equals("JUS MANGGA"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(true);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(false);}
       
       if(e.equals("JUS ALPUKAT"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(true);
                                      cbairmineral.setSelected(false);}
       
       if(e.equals("AIR MINERAL"))            {cbteh.setSelected(false);
                                      cbcappuchino.setSelected(false);
                                      cbjusmangga.setSelected(false);
                                      cbjusalpukat.setSelected(false);
                                      cbairmineral.setSelected(true);}
       
       ttotalharga.setText(f);
       tbayar.setText(g);
       tkembalian.setText(h);
    }//GEN-LAST:event_tabelpembayaranMouseClicked

    private void bbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihkanActionPerformed
        // TODO add your handling code here:
        tnomormeja.setText("");
        cbpaket.setSelectedIndex(0);
        tjumlahpaket.setText("");
        cbbebekgoreng.setSelected(false);
        cbayamgoreng.setSelected(false);
        cbikannila.setSelected(false);
        cbkentanggoreng.setSelected(false);
        cbrotibakar.setSelected(false);
        cbspageti.setSelected(false);
        
        cbteh.setSelected(false);
        cbcappuchino.setSelected(false);
        cbjusmangga.setSelected(false);
        cbjusalpukat.setSelected(false);
        cbairmineral.setSelected(false);
        
        ttotalharga.setText("");
        tbayar.setText("");
        tkembalian.setText("");
    }//GEN-LAST:event_bbersihkanActionPerformed

    private void struktransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_struktransaksiActionPerformed
        // TODO add your handling code here:
        mp.removeAll();
        mp.repaint();
        mp.revalidate();
        
        //add panel
        mp.add(mpdatapelanggan);
        mp.repaint();
        mp.revalidate();
    }//GEN-LAST:event_struktransaksiActionPerformed

    private void bsimpandatapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpandatapelangganActionPerformed
        // TODO add your handling code here:
        String sql = "insert into pelanggan values (?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, tnama.getText());
            stat.setString(2, tnotlp.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            tnama.requestFocus();
            kosong();
            datatable2();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_bsimpandatapelangganActionPerformed

    private void bubahdatapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahdatapelangganActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "update pelanggan set notlp=? where nama =?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, tnotlp.getText());
            
            stat.setString(2, tnama.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil diubah");
            kosong();
            tnama.requestFocus();
            datatable2();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+e);
        }
    }//GEN-LAST:event_bubahdatapelangganActionPerformed

    private void tabelpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpelangganMouseClicked
        // TODO add your handling code here:
        int bar = tabelpelanggan.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        
        tnama.setText(a);
        
        tnotlp.setText(b);
        
    }//GEN-LAST:event_tabelpelangganMouseClicked

    private void bhapusdatapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusdatapelangganActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok==0){
                String sql="delete from pelanggan where nama='"+tnama.getText()+"'";
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosong();
                    tnama.requestFocus();
                    datatable2();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
            }
    }//GEN-LAST:event_bhapusdatapelangganActionPerformed

    private void bbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbayarActionPerformed
        // TODO add your handling code here:
        try {
            String namaFile = "src/report/reportpembayaran.jasper";
            Connection conn = new koneksi().connect();
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false); //coba
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_bbayarActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        // TODO add your handling code here:
        try {
            String namaFile = "src/report/reportpelanggan.jasper";
            Connection conn = new koneksi().connect();
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false); //coba
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_bcetakActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        // TODO add your handling code here:
        try {
            String namaFile = "src/report/reportpembayaran.jasper";
            Connection conn = new koneksi().connect();
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false); //coba
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_penjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton bbayar;
    private javax.swing.JButton bbersihkan;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bhapusdata;
    private javax.swing.JButton bhapusdatapelanggan;
    private javax.swing.JButton bhitung;
    private javax.swing.JButton bhitung2;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bsimpandatapelanggan;
    private javax.swing.JButton btambah;
    private javax.swing.JButton bubahdatapelanggan;
    private javax.swing.JCheckBox cbairmineral;
    private javax.swing.JCheckBox cbayamgoreng;
    private javax.swing.JCheckBox cbbebekgoreng;
    private javax.swing.JCheckBox cbcappuchino;
    private javax.swing.JCheckBox cbikannila;
    private javax.swing.JCheckBox cbjusalpukat;
    private javax.swing.JCheckBox cbjusmangga;
    private javax.swing.JCheckBox cbkentanggoreng;
    private javax.swing.JComboBox<String> cbpaket;
    private javax.swing.JCheckBox cbrotibakar;
    private javax.swing.JCheckBox cbspageti;
    private javax.swing.JCheckBox cbteh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton laporan;
    private javax.swing.JPanel mp;
    private javax.swing.JPanel mpdatapelanggan;
    private javax.swing.JPanel mplaporan;
    private javax.swing.JPanel mppembayaran;
    private javax.swing.JPanel mppemesanan;
    private javax.swing.JButton pembayaran;
    private javax.swing.JButton pemesanan;
    private javax.swing.JButton penjualan;
    private javax.swing.JButton struktransaksi;
    private javax.swing.JTable tabelpelanggan;
    private javax.swing.JTable tabelpembayaran;
    private javax.swing.JTable tabelpesanan;
    private javax.swing.JTextField tbayar;
    private javax.swing.JTextField tjumlahpaket;
    private javax.swing.JTextField tkembalian;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnomormeja;
    private javax.swing.JTextField tnotlp;
    private javax.swing.JTextField ttotalharga;
    // End of variables declaration//GEN-END:variables
}
